### ISSUE TITLE
What's the best way to check if a string submitted matches any of the Alpha2 codes

### ISSUE THREAD

**Issue by emperorjm** [pouriya/keshvar#26]
I want to store the Country's Alpha2 code to a record and therefore the function will accept a string which I want to validate that it exists within the Alpha2 enum. I assume the current search functions currently don't allow for this.

**Comment by pouriya** [comment]
Since [`Alpha2` implements `TryFrom<&str>`](https://docs.rs/keshvar/0.3.0/keshvar/enum.Alpha2.html#impl-TryFrom%3C%26str%3E-for-Alpha2), You can use the following snippet to check if an input matches an `Alpha2` code or not:
```rust
let input = "fr".to_string();  // A correct alpha2 code
assert!(Alpha2::try_from(input.as_str()).is_ok());

let input = "rf".to_string();  // An invalid alpha2 code
assert!(Alpha2::try_from(input.as_str()).is_err());
```

<br/>

Note that if you do not include some countries (by changing `keshvar`'s default cargo features), **You may get errors for correct `Alpha2` codes** too!  
For example in the following `Cargo.toml` I only include countries of Asia region:
```toml
# ...
[dependencies]
# ...
keshvar = {version = "...", default-features = false, features = ["asia"]}
# ...
```
And I will get error if I try to convert `fr` (France) to `Alpha2`:
```rust
let input = "fr".to_string();
assert!(Alpha2::try_from(input.as_str()).is_err());
```

**Comment by emperorjm** [comment]
Thank you very much. Your suggestion worked perfectly.
